### PR TITLE
Feature/specific exceptions

### PR DESCRIPTION
**Pull request by psolyca**
Get ride of simple messages.

Test on this feature has been rework later...

### CODE REVIEW

**Comment by zyv** [comment]
Hi @psolyca,

Thanks for (trying) to work with me on this project! I have started by fixing the CI to also work on PRs, and introduced some pre-requisites for collaborative development:

1. Added `black` and reformatted the code
2. Moved from `nose` to `pytest`

I have taken the liberty to rebase this PR, and it seems to work now.

Regarding the PR:

Usually one starts introducing custom exceptions in the library to make sure that the consumers of the library can differentiate their own exceptions from the exceptions thrown by the library. Exceptions represent a rather questionable flow control technique, and Python dynamism doesn't necessarily make it any better, but for better or worse, the normal rule is to introduce a base exception that will be proprietary to the library, e.g. `huawei.ProtocolError(Exception)` and inherit from it - see e.g. `requests`:

https://requests.readthedocs.io/en/master/_modules/requests/exceptions/

This way all exceptions from the library can be caught as `except ProtocolError`. I like the idea of introducing a proper hierarchy, I have to admit that I was to careless about it and used standard Python exceptions out of laziness, to get stuff done quicker... but a good exception hierarchy takes some thought.

Another note that I have, is that you don't need to override `__str__` and store stuff in the exceptions - you can simply use inherited functionality for messages.

I will try to commit my version now, so that you can see what I mean. I'm not sure what we can do next... I've briefly had a look at your (other) draft PRs to better understand why you have opened this one- it's really cool that you're reversed the partial and sliced packets! 👍 

However, I would have implemented it differently - you seen to (ab)use exceptions as regular flow control. What I have in mind instead, is it to make `from_bytes` always return a `Packet`, but if it's incomplete prevent the parsing it by throwing exceptions. Maybe we could override `+=` to extend packets with new data...

I think the most productive would be for me try to understand your code and to write my own version / try to explain you why I think it's better - we could also arrange a video call if you think it's easier to discuss code rather than typing endless messages. The problem is, that I really won't have any time in the coming two weeks to seriously work with you on that... and after that I'll hopefully leave for vacation and will be unavailable for most of April.

So I really have a bad feeling of guilt. I'd really liked to help you, but I don't have the time - and I don't think that merging code "as is" would be a good idea...

--Yury.

**Comment by zyv** [comment]
@psolyca here is my version - also fixed formatter / linter errors.

One could derive additional exceptions like `MagicMismatchError(MismatchError)` for exceptions that

1. It even makes sense to catch
2. They are thrown more than once

... but it seems that for now there are none of those.

What do you think?

**Comment by psolyca** [comment]
I will have to reread all.

First I was trying to correct my PR after lint error I have seen.
But you write all this ^^

I was looking for a way to print "readable" messages after log parsing and I read your code.
For sure I am a complete noob in Python coding, I am self-taught so all information you provided in the previous message is good to take.

I was looking for a way to make differences between sliced or partial packages without using lots of attributs and checks thus I have the idea to use Exceptions. I know Exceptions is a bad practice for flow control but my idea was that malformed packages are error and could be handled with Exceptions.
In first place, this check was done in `Packet` and Exceptions were handled in called function but it was to heavy.
After many tries, I came to the solution of using `handle_data` method  in the `Packet` class . Using this method to check attributs could be another solution.

For the calls, I am sorry, I am not enough confident in my technical english to follow a conversation  ^^;

**Comment by psolyca** [comment]
Ok for your Exception. I understand the way you want it.

I will rebase my work on your master branch when this PR is merged and rework the message handling without exceptions.

**Comment by zyv** [comment]
> For sure I am a complete noob in Python coding

Being noob is not a problem - I know of nobody who was born with Python programming skills ;-) My worry is that I have too little time to support you, so you will get annoyed and disappointed about my bickering.

Thanks for the explanation of what your intention with the exceptions was. That was pretty much what I understood from the code. I need to find some time to think how I would have expressed it and make a suggestion. Thankfully I think you have some partial / sliced packet data in tests, do I could develop blindly. I think it should be possible to do it without exceptions for flow control, but also without too many checks - by raising exceptions inside of methods that should not be used if packet is incomplete and by overwriting "magic" methods. 

> For the calls, I am sorry, I am not enough confident in my technical english to follow a conversation ^^;

No problem - this was just a suggestion. I also speak fluent German and Russian, and I used to be fluent in French, but now I can only understand it I think - speaking would be too difficult after a 20 years break :-/ If any of those languages sound better to you, it could be an option :-)

> I will rebase my work on your master branch when this PR is merged and rework the message handling without exceptions.

Alright, thanks - I will squash and merge this PR now.

**Pull request merged**
